[package]
name = "ecom-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
metrics = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
governor = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
moka = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
tower-http = { workspace = true }
